In [45]:
import numpy as np
R1 = int(input("Enter the no of rows:"))
C1 = int(input("Enter the no of coloumn:"))
print("Enter the entries in a single line(sepearated by space): ")
entries = list(map(int, input().split()))
matrix_1 = np.array(entries).reshape(R1,C1)
print("Matrix_1: \n",matrix_1)


R2 = int(input("Enter the no of rows:"))
C2= int(input("Enter the no of coloumn:"))
print("Enter the entries in a single line(sepearated by space): ")
entries = list(map(int, input().split()))
matrix_2 = np.array(entries).reshape(R2,C2)
print("matrix_2: \n",matrix_2)

Enter the no of rows: 2
Enter the no of coloumn: 2


Enter the entries in a single line(sepearated by space): 


 1 2 3 4


Matrix_1: 
 [[1 2]
 [3 4]]


Enter the no of rows: 2
Enter the no of coloumn: 2


Enter the entries in a single line(sepearated by space): 


 0 1 2 0


matrix_2: 
 [[0 1]
 [2 0]]


In [46]:
#Dot.product

dot_prdt = np.dot(matrix_1,matrix_2)
print("dot.product of 2 matrices: \n",dot_prdt)


dot.product of 2 matrices: 
 [[4 1]
 [8 3]]


In [48]:
#transpose


print("Transpose of matrix_1: \n",matrix_1.transpose(), "\n Transpose of matrix_2: \n",matrix_2.transpose())


Transpose of matrix_1: 
 [[1 3]
 [2 4]] 
 Transpose of matrix_2: 
 [[0 2]
 [1 0]]


In [49]:
 #trace
    
print("Trace of matrix_1: \n",np.trace(matrix_1),"\n Trace of matrix_2: \n",np.trace(matrix_2))    


Trace of matrix_1: 
 5 
 Trace of matrix_2: 
 0


In [50]:
#rank

print("The rank of matrix_1 :",np.linalg.matrix_rank(matrix_1),"\n The rank of matrix_2 :",np.linalg.matrix_rank(matrix_2))

The rank of matrix_1 : 2 
 The rank of matrix_2 : 2


In [52]:
#determinent

print("The determinent of matrix_1 :",int(np.linalg.det(matrix_1)),"\n The determinent of matrix_2 :",int(np.linalg.det(matrix_2)))

The determinent of matrix_1 : -2 
 The determinent of matrix_2 : -2


In [53]:
#Inverse

print("The inverse of matrix_1 : \n",np.linalg.inv(matrix_1),"\n The inverse of matrix_2 : \n",np.linalg.inv(matrix_2))


The inverse of matrix_1 : 
 [[-2.   1. ]
 [ 1.5 -0.5]] 
 The inverse of matrix_2 : 
 [[0.  0.5]
 [1.  0. ]]


In [58]:
#Eigen values and eigen vectors

w1, v1 = np.linalg.eig(matrix_1)


print("The eigen values of matrix_1 : \n",w1)
print(" The eigen vectors of matrix_1:\n",v1)

w2 , v2 = np.linalg.eig(matrix_2)

print("The eigen values of matrix_2 : \n",w2)
print(" The eigen vectors of matrix_2:\n",v2)




The eigen values of matrix_1 : 
 [-0.37228132  5.37228132]
 The eigen vectors of matrix_1:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
The eigen values of matrix_2 : 
 [ 1.41421356 -1.41421356]
 The eigen vectors of matrix_2:
 [[ 0.57735027 -0.57735027]
 [ 0.81649658  0.81649658]]
